modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Booziiiah"

description='''
Adds a closet, a bear rug and taxidermy mounts.
'''

[[dependencies.${mod_id}]]
	modId="neoforge"
	type="required"
	versionRange="[${neo_version},)"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="minecraft"
	type="required"
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="wildernature"
	type="required"
	versionRange="[1.1.0,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="primal"
	type="required"
	versionRange="[1.0.0,)"
	ordering="NONE"
	side="BOTH"
